version: 2.0
jobs:
 build:
   steps:
     - checkout
     - run: 
         name: Install
         command: npm install
test: 
  steps:
    - checkout
    - run:
        name: Test
        command: npm test

